spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/library
    username: postgres
    password: postgres

server:
  servlet:
    context-path: /library

# Spring Securityのログを有効にする
logging.level.org.springframework.security: DEBUG
